"""Campaign Service — Campaign lifecycle management.

State machine: draft → running → paused → completed

Handles campaign creation, state transitions, email queuing,
and metrics computation. Supports both AI-generated and template-based emails.
"""

from datetime import datetime, timedelta
from typing import Dict, Any, Optional

from sqlalchemy.orm import Session
from sqlalchemy import func

import pytz

from database.models import Campaign, EmailSent, Lead, LeadScore, EmailAccount, Candidate, PaymentOrder
from core.logger import get_logger
from core.metrics import CAMPAIGNS_RUNNING
from services.email_campaign.email_generator_service import assign_style

logger = get_logger(__name__)

# Valid state transitions
VALID_TRANSITIONS = {
    "draft": ["running"],
    "running": ["paused", "completed"],
    "paused": ["running", "completed"],
    "completed": ["running"],
    # Restart (audit P24): only via restore_cancelled_work, which re-reserves
    # credits for the retired emails first.
    "cancelled": ["running"],
}


def create_campaign(
    db: Session,
    user_id: str,
    name: str,
    email_account_id: int,
    candidate_id: int,
    daily_limit: int = 20,
    subject_template: str = "",
    body_template: str = "",
    selected_styles: Optional[list] = None,
    user_timezone: str = "Asia/Kolkata",
    lead_limit: Optional[int] = None,
) -> Dict[str, Any]:
    """Create a new email campaign with JIT placeholder emails.

    In JIT mode (selected_styles provided): creates placeholder EmailSent rows for ALL
    leads (not just enriched ones). Content is generated by the worker just before sending.

    In legacy mode (no selected_styles): generates emails immediately for enriched leads only.

    Args:
        db: Database session.
        user_id: Owner user ID.
        name: Campaign name.
        email_account_id: Gmail account to send from.
        candidate_id: The candidate whose leads to pull from.
        daily_limit: Max emails per day.
        subject_template: Email subject template (legacy mode).
        body_template: Email body template (legacy mode).
        selected_styles: List of email styles for JIT AI generation.
        user_timezone: User's timezone for scheduling.
        lead_limit: Max leads to include (defaults to all available).

    Returns:
        Dict with campaign details and queued message count.
    """
    logger.info(
        "[CAMPAIGN] Creating campaign: %s (account=%d, candidate=%d, styles=%s)",
        name, email_account_id, candidate_id, selected_styles
    )

    # Verify email account exists
    account = db.query(EmailAccount).filter_by(id=email_account_id, user_id=user_id).first()
    if not account:
        raise ValueError(f"Email account {email_account_id} not found")

    # Fetch candidate. Scoped to the caller so nobody can run a campaign on
    # another user's candidate and lead list (audit PS-N17).
    candidate = db.query(Candidate).filter_by(id=candidate_id, user_id=user_id).first()
    if not candidate:
        raise ValueError(f"Candidate {candidate_id} not found")

    use_ai_generation = selected_styles and len(selected_styles) > 0

    # Create campaign
    campaign = Campaign(
        candidate_id=candidate_id,
        email_account_id=email_account_id,
        name=name,
        status="draft",
        subject_template=subject_template,
        body_template=body_template,
        user_timezone=user_timezone,
        selected_styles=selected_styles if use_ai_generation else None,
        generation_mode="ai" if use_ai_generation else "template",
    )
    db.add(campaign)
    db.flush()

    queued = 0
    failed = 0

    if use_ai_generation:
        # ── JIT Mode: Create placeholder rows for ALL leads, ordered by score ──
        # Score order here decides *which* leads make the lead_limit cut, not the
        # order they go out in. Send order is settled later, in campaign_worker's
        # _compute_schedule, which reads EmailSent.send_position — a column that
        # cannot exist yet, because the rows below are what create it.
        leads_query = (
            db.query(Lead)
            .filter(Lead.candidate_id == candidate_id)
            .outerjoin(LeadScore, LeadScore.lead_id == Lead.id)
            .order_by(LeadScore.overall_score.desc().nullslast(), Lead.id.asc())
        )
        if lead_limit:
            leads_query = leads_query.limit(lead_limit)

        all_leads = leads_query.all()

        for lead in all_leads:
            style = assign_style(lead, selected_styles)

            # If lead is already enriched, populate to_email and mark enriched
            already_enriched = lead.email and lead.email_verified
            email_sent = EmailSent(
                campaign_id=campaign.id,
                lead_id=lead.id,
                to_email=lead.email if already_enriched else None,
                subject=None,  # Generated JIT by the worker
                body=None,
                assigned_style=style,
                enrichment_status="enriched" if already_enriched else "pending",
                status="pending_enrichment",
            )
            db.add(email_sent)
            queued += 1

    else:
        # ── Legacy Mode: Generate emails immediately for enriched leads only ──
        enriched_leads = (
            db.query(Lead)
            .filter(
                Lead.candidate_id == candidate_id,
                Lead.email.isnot(None),
                Lead.email_verified == True,
            )
            .all()
        )

        for lead in enriched_leads:
            try:
                subject = subject_template.replace("{name}", lead.name or "")
                subject = subject.replace("{company}", lead.company or "")
                body = body_template.replace("{name}", lead.name or "")
                body = body.replace("{company}", lead.company or "")
                body = body.replace("{title}", lead.title or "")

                email_sent = EmailSent(
                    campaign_id=campaign.id,
                    lead_id=lead.id,
                    to_email=lead.email,
                    subject=subject,
                    body=body,
                    enrichment_status="enriched",
                    status="queued",
                )
                db.add(email_sent)
                queued += 1
            except Exception as e:
                logger.error("[CAMPAIGN] Failed to generate email for lead %s: %s", lead.name, str(e))
                failed += 1
                continue

    db.commit()

    logger.info(
        "[CAMPAIGN] Campaign #%d created: %d messages queued, %d failed (mode=%s)",
        campaign.id, queued, failed, "jit" if use_ai_generation else "legacy"
    )

    return {
        "campaign_id": campaign.id,
        "name": name,
        "status": "draft",
        "queued_messages": queued,
        "generation_mode": "ai" if use_ai_generation else "template",
        "failed_generations": failed,
        "email_account": account.email_address,
    }


def restore_cancelled_work(db: Session, campaign: Campaign) -> int:
    """Bring back what a cancelled campaign retired, as far as credits allow.

    Cancel returned the credits for every unsent email and retired those rows
    as 'expired'. Restarting re-reserves credits for as many as the wallet can
    cover (oldest first), puts them back in the queue, and restores their
    follow-ups. Returns how many first touches came back.
    """
    from services import credits as _credits
    owner = db.query(Candidate.user_id).filter(Candidate.id == campaign.candidate_id).scalar()
    retired = (
        db.query(EmailSent)
        .filter(EmailSent.campaign_id == campaign.id, EmailSent.status == "expired",
                EmailSent.followup_number == 0, EmailSent.is_test.isnot(True),
                EmailSent.replacement_for_id.is_(None))
        .order_by(EmailSent.id.asc())
        .all()
    )
    n = min(len(retired), _credits.available(db, owner) if owner else 0)
    if n <= 0:
        raise ValueError(
            "Nothing to restart: this campaign has no unsent emails left, or you have no credits free to cover them."
        )
    if _credits.reserve(db, owner, n, _credits.RESERVE_CAMPAIGN, campaign=campaign,
                        note="restart of a cancelled campaign") is None:
        raise ValueError("Not enough free credits to restart this campaign.")
    now = datetime.utcnow()
    for e in retired[:n]:
        e.status = "pending_enrichment"
        e.error_message = None
        e.status_changed_at = now
    db.query(EmailSent).filter(
        EmailSent.campaign_id == campaign.id, EmailSent.status == "cancelled_expired",
    ).update({EmailSent.status: "followup_pending", EmailSent.status_changed_at: now},
             synchronize_session=False)
    campaign.outcome = None
    campaign.completed_at = None
    db.commit()
    return n


def _scan_replies_before_restart(db: Session, campaign: Campaign) -> None:
    """Read the campaign's mailbox back to its first send before it starts
    again. Paused and cancelled campaigns used to get no reply checks, so a
    reply that came in meanwhile did not cancel its follow-up, which then went
    out on resume (audit NEW-03, PS-N18). Best effort: a failure here is
    logged, and the send-time checks still apply."""
    from services.email_campaign.campaign_worker import check_mailbox_replies
    account = db.get(EmailAccount, campaign.email_account_id) if campaign.email_account_id else None
    if account is None:
        return
    first_sent = (
        db.query(func.min(EmailSent.sent_at))
        .filter(EmailSent.campaign_id == campaign.id, EmailSent.sent_at.isnot(None))
        .scalar()
    )
    if first_sent is None:
        return
    try:
        replies, bounces = check_mailbox_replies(db, account, after_epoch=int(first_sent.timestamp()))
        logger.info("[CAMPAIGN] Pre-restart reply scan for campaign #%d: replies=%d bounces=%d",
                    campaign.id, replies, bounces)
    except Exception as e:  # noqa: BLE001 - never block the user's resume on this
        db.rollback()
        logger.warning("[CAMPAIGN] Pre-restart reply scan failed for campaign #%d: %s", campaign.id, e)


def _next_business_morning(campaign: Campaign, now: datetime) -> datetime:
    from services.email_campaign.campaign_worker import _campaign_tz, _push_to_business_hours
    tz = _campaign_tz(campaign)
    local = now.replace(tzinfo=pytz.utc).astimezone(tz) + timedelta(days=1)
    morning = local.replace(hour=9, minute=0, second=0, microsecond=0)
    return _push_to_business_hours(morning.astimezone(pytz.utc).replace(tzinfo=None), tz)


def transition_campaign(db: Session, campaign_id: int, target_status: str,
                        actor: str = "user") -> Dict[str, Any]:
    """Transition a campaign to a new state.

    actor: who asked, recorded as paused_by on a pause ('user', 'system', or
    an admin user id).

    Raises:
        ValueError: If transition is invalid.
    """
    campaign = db.query(Campaign).filter_by(id=campaign_id).first()
    if not campaign:
        raise ValueError(f"Campaign {campaign_id} not found")

    valid = VALID_TRANSITIONS.get(campaign.status, [])
    if target_status not in valid:
        raise ValueError(
            f"Invalid transition: {campaign.status} -> {target_status}. "
            f"Valid transitions: {valid}"
        )

    old_status = campaign.status
    restarting = old_status in ("paused", "cancelled") and target_status == "running"
    if old_status != "draft" and target_status == "running":
        # A campaign from before per-campaign reservations holds none, so
        # nothing capped it at what was paid (PP-P26). Reserve its unsent
        # emails from the wallet first; raises ValueError when none can be.
        from services.email_campaign.campaign_worker import adopt_legacy_reservation
        adopt_legacy_reservation(db, campaign)
    if restarting:
        _scan_replies_before_restart(db, campaign)
    if old_status == "cancelled" and target_status == "running":
        restore_cancelled_work(db, campaign)  # raises ValueError if nothing can be restored
        now = datetime.utcnow()
        # Restored follow-ups wait for at least the next business morning, so
        # none goes out before a reply to its first email could be seen.
        morning = _next_business_morning(campaign, now)
        db.query(EmailSent).filter(
            EmailSent.campaign_id == campaign.id,
            EmailSent.status == "followup_pending",
            (EmailSent.scheduled_at.is_(None)) | (EmailSent.scheduled_at < morning),
        ).update({EmailSent.scheduled_at: morning}, synchronize_session=False)
        # A plan that ran out while cancelled gets its original length again:
        # otherwise the restart finished itself on the next cycle (PS-N18).
        if campaign.expires_at and campaign.expires_at <= now:
            length = (campaign.expires_at - campaign.started_at) if campaign.started_at else timedelta(days=8)
            campaign.expires_at = now + max(length, timedelta(days=1))
    campaign.status = target_status
    db.commit()

    logger.info("[CAMPAIGN] Campaign #%d: %s -> %s", campaign_id, old_status, target_status,
                extra={"event": "campaign_state_change", "campaign_id": campaign_id})

    if target_status == "running":
        CAMPAIGNS_RUNNING.inc()
        # First time the campaign actually launches — record started_at
        # (kept across pause/resume cycles so we always know the original launch).
        if campaign.started_at is None:
            now = datetime.utcnow()
            campaign.started_at = now
            # Set expiry for duration-limited plans (e.g. email_50 = 8 days)
            try:
                from services.order_links import order_for_campaign
                outreach_order = order_for_campaign(db, campaign)
                if outreach_order:
                    payment_order = (
                        db.query(PaymentOrder)
                        .filter_by(outreach_order_id=outreach_order.id, status="paid")
                        .order_by(PaymentOrder.created_at.desc())
                        .first()
                    )
                    if payment_order and payment_order.plan_id:
                        from core.pricing import get_plan as _get_plan
                        plan = _get_plan(payment_order.plan_id)
                        if plan.duration_days > 0:
                            campaign.expires_at = now + timedelta(days=plan.duration_days)
                            logger.info("[CAMPAIGN] Campaign #%d expires_at set to %s (%d-day plan)",
                                        campaign_id, campaign.expires_at, plan.duration_days)
            except Exception as e:
                logger.warning("[CAMPAIGN] Could not set expires_at for campaign #%d: %s", campaign_id, e)
            db.commit()
    elif old_status == "running":
        CAMPAIGNS_RUNNING.dec()

    if target_status == "completed":
        # Same settlement as the worker: retire unsent work, return its
        # credits, close the order.
        from services.email_campaign.campaign_worker import finish_campaign
        finish_campaign(db, campaign, reason=f"completed by {actor}")

    # Record who paused and when (audit P40: nobody could say why a campaign stopped)
    if old_status == "running" and target_status == "paused":
        campaign.paused_at = datetime.utcnow()
        campaign.paused_by = actor
        campaign.pause_reason = "user" if actor == "user" else "admin"
        from services.email_campaign.outcomes import record_pause_event
        record_pause_event(db, campaign)
        db.commit()
        logger.info("[CAMPAIGN] Paused campaign #%d by %s, paused_at=%s",
                    campaign_id, actor, campaign.paused_at)

    # Queue campaign bootstrap (scheduler initialization) if transitioning to "running"
    if target_status == "running":
        # Safety: check that there are emails to process (queued or pending_enrichment)
        email_count = db.query(func.count(EmailSent.id)).filter(
            EmailSent.campaign_id == campaign_id,
            EmailSent.status.in_(["queued", "pending_enrichment"]),
        ).scalar() or 0

        if email_count == 0:
            # Revert status — nothing to send
            campaign.status = old_status
            db.commit()
            raise ValueError("Cannot launch campaign: no emails in queue.")

        # Pre-compute schedule timestamps for all emails (queued + pending_enrichment)
        from services.email_campaign.campaign_worker import compute_campaign_schedule
        # A resumed or restarted campaign starts inside the 9-5 window, not
        # 30-180 seconds from now at any hour (PS-N16).
        compute_campaign_schedule(db, campaign_id, resume=restarting)
        logger.info("[CAMPAIGN] Computed schedule for campaign #%d (emails=%d)",
                    campaign_id, email_count)

    # Resume: compute_campaign_schedule above already re-planned every unsent
    # email starting from now. This used to ALSO shift the new schedule forward
    # by the pause length, so a 22-day pause meant nothing sent for 22 more
    # days after Resume (audit P02). The recompute is the whole compensation.
    if old_status == "paused" and target_status == "running":
        campaign.paused_at = None
        campaign.paused_by = None
        campaign.pause_reason = None
        db.commit()
        logger.info("[CAMPAIGN] Resumed campaign #%d", campaign_id)

    # Sync order status + record funnel stage timestamps (10/11/12).
    try:
        # OutreachOrder comes from the module-level import. A local
        # `from database.models import OutreachOrder` here made the name local
        # to the WHOLE function, so the earlier read on first launch raised
        # UnboundLocalError. That was caught and logged, so expires_at was
        # never set and 8-day plans (email_50) never expired.
        from services.stage_tracking import safe_mark_stage
        from services.order_links import order_for_campaign
        order = order_for_campaign(db, campaign)
        if order:
            order_status_map = {
                "running": "campaign_running",
                # A paused campaign was already built + launched — route the user to
                # the dashboard (where pause reason + reconnect banners live), NOT back
                # to /campaign/setup, which created an infinite "Resume -> setup" loop.
                "paused": "campaign_running",
                "completed": "completed",
            }
            new_order_status = order_status_map.get(target_status)
            if new_order_status and order.status != new_order_status:
                order.status = new_order_status
                log = list(order.action_log or [])
                log.append({"ts": datetime.utcnow().isoformat(), "msg": f"Campaign {old_status} -> {target_status}"})
                order.action_log = log
                order.updated_at = datetime.utcnow()
                db.commit()

            # Funnel stages — recorded on the order regardless of status mapping.
            stage_map = {
                "running": "campaign_launched",
                "paused": "campaign_paused",
                "completed": "campaign_completed",
            }
            funnel_stage = stage_map.get(target_status)
            if funnel_stage:
                safe_mark_stage(db, str(order.user_id), funnel_stage,
                                campaign_id=campaign_id)
    except Exception as e:
        logger.error("[CAMPAIGN] Failed to sync order status: %s", e)

    return {
        "campaign_id": campaign_id,
        "old_status": old_status,
        "new_status": target_status,
    }


# What a customer is told about an email that did not go out (audit P22).
# error_message is internal (stack text, provider payloads); these are not.
_NO_EMAIL_MARKERS = ("apollo could not find", "lead not found")
_AUTH_MARKERS = ("token refresh failed", "auth expired", "must reconnect", '"code": 401',
                 "insufficient authentication scopes", "email account not found")


def customer_failure_reason(status: Optional[str], error_message: Optional[str]) -> Optional[str]:
    msg = (error_message or "").lower()
    if status == "bounced":
        return "The address bounced. We queued a replacement contact where we could."
    if status == "expired":
        return "The campaign ended before this email was sent. Its credit was returned."
    if status != "failed":
        return None
    if any(m in msg for m in _NO_EMAIL_MARKERS):
        return "No verified email address exists for this contact, so it was skipped."
    if any(m in msg for m in _AUTH_MARKERS):
        return "Gmail disconnected. Reconnect Gmail to keep sending."
    if "enrichment" in msg:
        return "We could not verify this contact's email, so it was skipped."
    if "cancelled" in msg:
        return "The campaign was cancelled before this email was sent."
    return "Gmail did not accept this email."


def is_skipped_no_email(error_message: Optional[str]) -> bool:
    msg = (error_message or "").lower()
    return any(m in msg for m in _NO_EMAIL_MARKERS) or "enrichment" in msg


def get_campaign_metrics(db: Session, campaign_id: int) -> Dict[str, Any]:
    """Compute metrics for a campaign."""
    campaign = db.query(Campaign).filter_by(id=campaign_id).first()
    if not campaign:
        raise ValueError(f"Campaign {campaign_id} not found")

    total = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id
    ).scalar() or 0

    sent = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status.in_(["sent", "replied"]),
    ).scalar() or 0

    failed = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "failed",
    ).scalar() or 0

    replied = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "replied",
    ).scalar() or 0

    bounced = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "bounced",
    ).scalar() or 0

    positive = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.reply_sentiment == "positive",
    ).scalar() or 0

    negative = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.reply_sentiment == "negative",
    ).scalar() or 0

    neutral_replies = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.reply_sentiment == "neutral",
    ).scalar() or 0

    queued = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status.in_(["queued", "scheduled"]),
    ).scalar() or 0

    # JIT enrichment metrics
    pending_enrichment = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "pending_enrichment",
    ).scalar() or 0

    enriched = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.enrichment_status == "enriched",
    ).scalar() or 0

    enrichment_skipped = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.enrichment_status == "skipped",
    ).scalar() or 0

    reply_rate = (replied / sent * 100) if sent > 0 else 0.0

    # Split "Failed" (audit P22): most failures were leads with no email at
    # all, which is a skip, not Studojo breaking the campaign.
    failed_msgs = [m for (m,) in db.query(EmailSent.error_message).filter(
        EmailSent.campaign_id == campaign_id, EmailSent.status == "failed")]
    skipped_no_email = sum(1 for m in failed_msgs if is_skipped_no_email(m))

    # "X of Y delivered" for the finished-campaign banner (P20): first touches only.
    first_touch = (EmailSent.followup_number == 0) & (EmailSent.is_test.isnot(True))
    first_total = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id, first_touch).scalar() or 0
    first_delivered = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id, first_touch,
        EmailSent.status.in_(["sent", "replied", "bounced"])).scalar() or 0
    last_sent_at = db.query(func.max(EmailSent.sent_at)).filter(
        EmailSent.campaign_id == campaign_id).scalar()

    metrics = {
        "campaign_id": campaign_id,
        "campaign_name": campaign.name,
        "status": campaign.status,
        "user_timezone": campaign.user_timezone or "Asia/Kolkata",
        "emails_total": total,
        "emails_queued": queued,
        "emails_pending_enrichment": pending_enrichment,
        "emails_enriched": enriched,
        "emails_enrichment_skipped": enrichment_skipped,
        "emails_sent": sent,
        "emails_failed": failed,
        "emails_replied": replied,
        "emails_bounced": bounced,
        "emails_positive": positive,
        "emails_negative": negative,
        "emails_neutral": neutral_replies,
        "reply_rate": round(reply_rate, 2),
        "emails_skipped_no_email": skipped_no_email,
        # Contacts we found a replacement for (audit P33), so the dashboard can
        # say "N couldn't be reached, we replaced K" instead of just under-delivering.
        "replacements_added": db.query(func.count(EmailSent.id)).filter(
            EmailSent.campaign_id == campaign_id,
            EmailSent.replacement_reason == "enrichment_exhausted").scalar() or 0,
        # P01: 'delivered' | 'degraded' | 'cancelled' once finished.
        "outcome": campaign.outcome,
        "emails_failed_other": failed - skipped_no_email,
        "first_touch_total": first_total,
        "first_touch_delivered": first_delivered,
        "last_sent_at": last_sent_at.isoformat() if last_sent_at else None,
        # The real sending rate (P41: the dashboard said 5-7/day).
        "daily_limit": campaign.daily_limit,
        # Why it stopped (P40).
        "paused_at": campaign.paused_at.isoformat() if campaign.paused_at else None,
        "paused_by": campaign.paused_by,
        "pause_reason": campaign.pause_reason,
        # What this campaign holds of the wallet (P39).
        "credits_reserved": campaign.credits_reserved,
        "credits_released": campaign.credits_released or 0,
    }

    logger.info("[CAMPAIGN] Metrics for #%d: %s", campaign_id, metrics)

    return metrics
