"""Campaign Service — Campaign lifecycle management.

State machine: draft → running → paused → completed

Handles campaign creation, state transitions, email queuing,
and metrics computation. Supports both AI-generated and template-based emails.
"""

from datetime import datetime
from typing import Dict, Any, Optional

from sqlalchemy.orm import Session
from sqlalchemy import func

from database.models import Campaign, EmailSent, Lead, LeadScore, EmailAccount, Candidate
from core.logger import get_logger
from core.metrics import CAMPAIGNS_RUNNING, EMAILS_SENT_TOTAL
from services.email_campaign.email_generator_service import assign_style

logger = get_logger(__name__)

# Valid state transitions
VALID_TRANSITIONS = {
    "draft": ["running"],
    "running": ["paused", "completed"],
    "paused": ["running", "completed"],
    "completed": ["running"],
}


def create_campaign(
    db: Session,
    user_id: str,
    name: str,
    email_account_id: int,
    candidate_id: int,
    daily_limit: int = 20,
    subject_template: str = "",
    body_template: str = "",
    selected_styles: Optional[list] = None,
    user_timezone: str = "Asia/Kolkata",
    lead_limit: Optional[int] = None,
) -> Dict[str, Any]:
    """Create a new email campaign with JIT placeholder emails.

    In JIT mode (selected_styles provided): creates placeholder EmailSent rows for ALL
    leads (not just enriched ones). Content is generated by the worker just before sending.

    In legacy mode (no selected_styles): generates emails immediately for enriched leads only.

    Args:
        db: Database session.
        user_id: Owner user ID.
        name: Campaign name.
        email_account_id: Gmail account to send from.
        candidate_id: The candidate whose leads to pull from.
        daily_limit: Max emails per day.
        subject_template: Email subject template (legacy mode).
        body_template: Email body template (legacy mode).
        selected_styles: List of email styles for JIT AI generation.
        user_timezone: User's timezone for scheduling.
        lead_limit: Max leads to include (defaults to all available).

    Returns:
        Dict with campaign details and queued message count.
    """
    logger.info(
        "[CAMPAIGN] Creating campaign: %s (account=%d, candidate=%d, styles=%s)",
        name, email_account_id, candidate_id, selected_styles
    )

    # Verify email account exists
    account = db.query(EmailAccount).filter_by(id=email_account_id).first()
    if not account:
        raise ValueError(f"Email account {email_account_id} not found")

    # Fetch candidate
    candidate = db.query(Candidate).filter_by(id=candidate_id).first()
    if not candidate:
        raise ValueError(f"Candidate {candidate_id} not found")

    use_ai_generation = selected_styles and len(selected_styles) > 0

    # Create campaign
    campaign = Campaign(
        candidate_id=candidate_id,
        email_account_id=email_account_id,
        name=name,
        status="draft",
        subject_template=subject_template,
        body_template=body_template,
        user_timezone=user_timezone,
        selected_styles=selected_styles if use_ai_generation else None,
        generation_mode="ai" if use_ai_generation else "template",
    )
    db.add(campaign)
    db.flush()

    queued = 0
    failed = 0

    if use_ai_generation:
        # ── JIT Mode: Create placeholder rows for ALL leads, ordered by score ──
        leads_query = (
            db.query(Lead)
            .filter(Lead.candidate_id == candidate_id)
            .outerjoin(LeadScore, LeadScore.lead_id == Lead.id)
            .order_by(LeadScore.overall_score.desc().nullslast(), Lead.id.asc())
        )
        if lead_limit:
            leads_query = leads_query.limit(lead_limit)

        all_leads = leads_query.all()

        for lead in all_leads:
            style = assign_style(lead, selected_styles)

            # If lead is already enriched, populate to_email and mark enriched
            already_enriched = lead.email and lead.email_verified
            email_sent = EmailSent(
                campaign_id=campaign.id,
                lead_id=lead.id,
                to_email=lead.email if already_enriched else None,
                subject=None,  # Generated JIT by the worker
                body=None,
                assigned_style=style,
                enrichment_status="enriched" if already_enriched else "pending",
                status="pending_enrichment",
            )
            db.add(email_sent)
            queued += 1

    else:
        # ── Legacy Mode: Generate emails immediately for enriched leads only ──
        enriched_leads = (
            db.query(Lead)
            .filter(
                Lead.candidate_id == candidate_id,
                Lead.email.isnot(None),
                Lead.email_verified == True,
            )
            .all()
        )

        for lead in enriched_leads:
            try:
                subject = subject_template.replace("{name}", lead.name or "")
                subject = subject.replace("{company}", lead.company or "")
                body = body_template.replace("{name}", lead.name or "")
                body = body.replace("{company}", lead.company or "")
                body = body.replace("{title}", lead.title or "")

                email_sent = EmailSent(
                    campaign_id=campaign.id,
                    lead_id=lead.id,
                    to_email=lead.email,
                    subject=subject,
                    body=body,
                    enrichment_status="enriched",
                    status="queued",
                )
                db.add(email_sent)
                queued += 1
            except Exception as e:
                logger.error("[CAMPAIGN] Failed to generate email for lead %s: %s", lead.name, str(e))
                failed += 1
                continue

    db.commit()

    logger.info(
        "[CAMPAIGN] Campaign #%d created: %d messages queued, %d failed (mode=%s)",
        campaign.id, queued, failed, "jit" if use_ai_generation else "legacy"
    )

    return {
        "campaign_id": campaign.id,
        "name": name,
        "status": "draft",
        "queued_messages": queued,
        "generation_mode": "ai" if use_ai_generation else "template",
        "failed_generations": failed,
        "email_account": account.email_address,
    }


def transition_campaign(db: Session, campaign_id: int, target_status: str) -> Dict[str, Any]:
    """Transition a campaign to a new state.

    Raises:
        ValueError: If transition is invalid.
    """
    campaign = db.query(Campaign).filter_by(id=campaign_id).first()
    if not campaign:
        raise ValueError(f"Campaign {campaign_id} not found")

    valid = VALID_TRANSITIONS.get(campaign.status, [])
    if target_status not in valid:
        raise ValueError(
            f"Invalid transition: {campaign.status} -> {target_status}. "
            f"Valid transitions: {valid}"
        )

    old_status = campaign.status
    campaign.status = target_status
    db.commit()

    logger.info("[CAMPAIGN] Campaign #%d: %s -> %s", campaign_id, old_status, target_status,
                extra={"event": "campaign_state_change", "campaign_id": campaign_id})

    if target_status == "running":
        CAMPAIGNS_RUNNING.inc()
    elif old_status == "running":
        CAMPAIGNS_RUNNING.dec()

    # Record pause time when pausing
    if old_status == "running" and target_status == "paused":
        campaign.paused_at = datetime.utcnow()
        db.commit()
        logger.info("[CAMPAIGN] Paused campaign #%d, paused_at=%s", campaign_id, campaign.paused_at)

    # Queue campaign bootstrap (scheduler initialization) if transitioning to "running"
    if target_status == "running":
        # Safety: check that there are emails to process (queued or pending_enrichment)
        email_count = db.query(func.count(EmailSent.id)).filter(
            EmailSent.campaign_id == campaign_id,
            EmailSent.status.in_(["queued", "pending_enrichment"]),
        ).scalar() or 0

        if email_count == 0:
            # Revert status — nothing to send
            campaign.status = old_status
            db.commit()
            raise ValueError("Cannot launch campaign: no emails in queue.")

        # Pre-compute schedule timestamps for all emails (queued + pending_enrichment)
        from services.email_campaign.campaign_worker import compute_campaign_schedule
        compute_campaign_schedule(db, campaign_id)
        logger.info("[CAMPAIGN] Computed schedule for campaign #%d (emails=%d)",
                    campaign_id, email_count)

    # Handle pause → running (resume): shift schedules forward by pause duration
    if old_status == "paused" and target_status == "running" and campaign.paused_at:
        pause_duration = (datetime.utcnow() - campaign.paused_at).total_seconds()
        from services.email_campaign.campaign_worker import shift_schedule_forward
        shift_schedule_forward(db, campaign_id, pause_duration)
        campaign.paused_at = None
        db.commit()
        logger.info("[CAMPAIGN] Resumed campaign #%d, shifted schedule by %.0f seconds",
                    campaign_id, pause_duration)

    # Sync order status
    try:
        from database.models import OutreachOrder
        order = db.query(OutreachOrder).filter_by(campaign_id=campaign_id).first()
        if order:
            order_status_map = {
                "running": "campaign_running",
                "paused": "campaign_setup",
                "completed": "completed",
            }
            new_order_status = order_status_map.get(target_status)
            if new_order_status and order.status != new_order_status:
                order.status = new_order_status
                log = list(order.action_log or [])
                log.append({"ts": datetime.utcnow().isoformat(), "msg": f"Campaign {old_status} -> {target_status}"})
                order.action_log = log
                order.updated_at = datetime.utcnow()
                db.commit()
    except Exception as e:
        logger.error("[CAMPAIGN] Failed to sync order status: %s", e)

    return {
        "campaign_id": campaign_id,
        "old_status": old_status,
        "new_status": target_status,
    }


def get_campaign_metrics(db: Session, campaign_id: int) -> Dict[str, Any]:
    """Compute metrics for a campaign."""
    campaign = db.query(Campaign).filter_by(id=campaign_id).first()
    if not campaign:
        raise ValueError(f"Campaign {campaign_id} not found")

    total = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id
    ).scalar() or 0

    sent = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status.in_(["sent", "replied"]),
    ).scalar() or 0

    failed = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "failed",
    ).scalar() or 0

    replied = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "replied",
    ).scalar() or 0

    bounced = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "bounced",
    ).scalar() or 0

    positive = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.reply_sentiment == "positive",
    ).scalar() or 0

    negative = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.reply_sentiment == "negative",
    ).scalar() or 0

    neutral_replies = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.reply_sentiment == "neutral",
    ).scalar() or 0

    queued = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status.in_(["queued", "scheduled"]),
    ).scalar() or 0

    # JIT enrichment metrics
    pending_enrichment = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.status == "pending_enrichment",
    ).scalar() or 0

    enriched = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.enrichment_status == "enriched",
    ).scalar() or 0

    enrichment_skipped = db.query(func.count(EmailSent.id)).filter(
        EmailSent.campaign_id == campaign_id,
        EmailSent.enrichment_status == "skipped",
    ).scalar() or 0

    reply_rate = (replied / sent * 100) if sent > 0 else 0.0

    metrics = {
        "campaign_id": campaign_id,
        "campaign_name": campaign.name,
        "status": campaign.status,
        "emails_total": total,
        "emails_queued": queued,
        "emails_pending_enrichment": pending_enrichment,
        "emails_enriched": enriched,
        "emails_enrichment_skipped": enrichment_skipped,
        "emails_sent": sent,
        "emails_failed": failed,
        "emails_replied": replied,
        "emails_bounced": bounced,
        "emails_positive": positive,
        "emails_negative": negative,
        "emails_neutral": neutral_replies,
        "reply_rate": round(reply_rate, 2),
    }

    logger.info("[CAMPAIGN] Metrics for #%d: %s", campaign_id, metrics)

    return metrics
